 default:
  autostart: false
  cache: false
  client: kvm-local
  cloudinit: true
  cpuhotplug: false
  cpumodel: host-model
  diskinterface: virtio
  disks:
  - default: true
    size: 10
  disksize: 10
  diskthin: true
  enableroot: true
  guestid: guestrhel764
  insecure: true
  jenkinsmode: podman
  keep_networks: false
  memory: 512
  memoryhotplug: false
  nested: true
  nets:
  - default
  networkwait: 0
  notify: false
  notifymethods:
  - pushbullet
  numcpus: 2
  pool: default
  privatekey: false
  reservedns: false
  reservehost: false
  reserveip: false
  rhnregister: false
  rhnserver: https://subscription.rhsm.redhat.com
  rhnunregister: false
  rng: false
  sharedkey: false
  start: true
  storemetadata: false
  tempkey: false
  tpm: false
  tunnel: false
  tunneldir: /var/www/html
  tunnelport: 22
  tunneluser: root
  vmrules_strict: false
  vnc: true
  wait: false
  waittimeout: 0
  yamlinventory: false
  zerotier_kubelet: false
srv:
  host: 192.168.168.1
  pool: default
  protocol: ssh
  type: kvm
  user: dustin
  enabled: true
kvm-local:
  host: localhost
  user: root
  protocol: ssh
  url: qemu:///system
  pool: default
  type: kvm
  enabled: true
rembot-ts:
  host: 100.89.186.70
  pool: default
  protocol: ssh
  type: kvm
  user: dustin
srv-ts:
  host: 100.123.211.36
  user: dustin
  protocol: ssh
  pool: default
  type: kvm